# Chapter 01: Coding Our First Neurons

## A Single Neuron

In [1]:
# A single neuron with 3 inputs
# For each input, there is an associated weight
# For each neuron, there is one bias
inputs = [1, 2, 3]
weights = [0.2, 0.9, -0.5]
bias = 3.3

# Output is the sum of weighted sum of inputs & bias
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

3.8


## A Layer of Neurons

In [2]:
# A Layer of 3 neurons with 4 inputs
# Each neuron has a set of weights associated with the set of inputs & one bias
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,
    
    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,
    
    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3,
]

print(outputs)

[4.8, 1.21, 2.385]


In [3]:
# A Layer of 3 neurons with 4 inputs
# Each neuron has a set of weights associated with the set of inputs & one bias
# Changed the code to use loops instead of hardcoded operations
inputs = [1, 2, 3, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]
biases = [2, 3, 0.5]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    # Add weighted inputs
    for input_, weight in zip(inputs, neuron_weights):
        neuron_output += input_ * weight
    # Add bias
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
    
print(layer_outputs)

[4.8, 1.21, 2.385]


## Tensors, Arrays and Vectors

In [4]:
import numpy as np

# list
# type = 1D Array, Vector
l = [1, 5, 6, 2]
print(f"Shape of l: {np.shape(l)}")

Shape of l: (4,)


In [5]:
# list of lists
# type = 2D Array, Matrix
lol = [[1, 5, 6, 2],
       [3, 2, 1, 3]]
print(f"Shape of lol: {np.shape(lol)}")

Shape of lol: (2, 4)


In [6]:
# list of list of lists
# type = 3D Array
lolol = [[[1, 5, 6, 2],
          [3, 2, 1, 3]],
         [[5, 2, 1, 2],
          [6, 4, 8, 4]],
         [[2, 8, 5, 3],
          [1, 1, 9, 4]]
        ]
print(f"Shape of lolol: {np.shape(lolol)}")

Shape of lolol: (3, 2, 4)


## Dot Product and Vector Addition

In [7]:
# vectors
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


## A Single Neuron with NumPy

In [8]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = np.dot(weights, inputs) + bias
print(output)

4.8


## A Layer of Neurons with NumPy

In [9]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]
biases = [2.0, 3.0, 0.5]

# NB: matrix should come first as argument for np.dot()
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


## A Batch of Data

In [10]:
import numpy as np

# Input Data -> Sample
# type = 1D Array, Vector
sample = [1, 5, 6, 2]
print(f"Shape of sample: {np.shape(sample)}")

Shape of sample: (4,)


In [11]:
# Input Data -> Batch
# type = 2D Array, Matrix
batch = [
    [1, 5, 6, 2],
    [3, 2, 1, 3],
    [5, 2, 1, 2],
    [6, 4, 8, 4],
    [2, 8, 5, 3],
    [1, 1, 9, 4],
    [6, 6, 0, 4],
    [8, 7, 6, 4],
]
print(f"Shape of batch: {np.shape(batch)}")

Shape of batch: (8, 4)


## Matrix Product

#### The matrix product is an operation in which we have 2 matrices, and we are performing dot products of all combinations of rows from the first matrix and the columns of the 2nd matrix, resulting in a matrix of those atomic dot products.

#### In the case of Neural Networks, two matrices are Matrix of inputs (input data as a batch) & Matrix of weights.

## Transposition for the Matrix Product

#### NumPy does not have a dedicated method to perform Matrix Product. Both Dot Product and Matrix Product are implemented in a single method: `np.dot()`.

#### A dot product of two vectors equals the matrix product of a row and a column vector (row and column vectors are matrices with one dimension = 1. We take first vector and convert it into row vector. In order to obtain column vector, we use Transposition after converting 2nd vector to row vector. The output of Matrix Product will be a matrix containing single value i.e. 1 x 1 matrix.

$\overrightarrow{a} \cdot \overrightarrow{b} = a b^T$

#### Matrix Product of two arrays will be a Matrix of dot products of all combinations of row and column vectors.


In [12]:
import numpy as np

# Create row vector from list
# A row vector is a matrix with 1 row & n columns i.e. an array of shape (1, n)
# To transform a list into a matrix containing a single row
# (perform an equivalent operation of turning a vector into row vector),

# Method 1: put list inside brackets & convert to numpy array
a = [1, 2, 3, 4]
row_vector = np.array([a])
print(row_vector)
print(row_vector.shape)

# Method 2: put list inside brackets & convert to numpy array
a = [1, 2, 3, 4]
row_vector = np.expand_dims(np.array(a), axis=0)
print(row_vector)
print(row_vector.shape)

[[1 2 3 4]]
(1, 4)
[[1 2 3 4]]
(1, 4)


In [13]:
# Create column vector from list
# A column vector is a matrix with n rows & 1 column i.e. an array of shape (n, 1)
# To transform a list into a matrix containing a single column
# (perform an equivalent operation of turning a vector into column vector),

# Method 1: put list inside brackets, convert to numpy array & perform Transposition
b = [1, 2, 3, 4]
column_vector = np.array([b]).T
print(column_vector)
print(column_vector.shape)

# Method 2: put list inside brackets, convert to numpy array & perform Transposition
b = [1, 2, 3, 4]
column_vector = np.expand_dims(np.array(b), axis=1)
print(column_vector)
print(column_vector.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [14]:
a = [1, 2, 3, 4]
b = [3, 4, 5, 6]

a = np.array([a])
b = np.array([b]).T

np.dot(a, b)

array([[50]])