# Chapter 02: Adding Layers

![Input layer with 4 features into a hidden layer with 3 neurons](images/image-05.png "Input layer with 4 features into a hidden layer with 3 neurons")

In [1]:
import numpy as np

inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8],
]
weights_1 = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87],
]
biases_1 = [2.0, 3.0, 0.5]

layer1_outputs = np.dot(inputs, np.array(weights_1).T) + biases_1
print(f"layer1_outputs: \n{layer1_outputs}")

# Add one more layer
weights_2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13],
]
biases_2 = [-1.0, 2.0, -0.5]

layer2_outputs = np.dot(layer1_outputs, np.array(weights_2).T) + biases_2
print(f"layer2_outputs: \n{layer2_outputs}")

layer1_outputs: 
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
layer2_outputs: 
[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


![4 features input into 2 hidden layers of 3 neurons each](images/image-06.png "4 features input into 2 hidden layers of 3 neurons each")